-- 1. تنظيف الجداول القديمة (لإعادة الإنشاء بشكل نظيف)
DROP TABLE IF EXISTS submissions CASCADE;
DROP TABLE IF EXISTS content CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2. إنشاء جدول المستخدمين
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'student', -- 'admin' أو 'student'
    name TEXT NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. إنشاء جدول المحتوى (الملفات، المهام، الاختبارات)
CREATE TABLE content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL, -- 'file', 'task', 'quiz'
    deadline TEXT,
    file_data TEXT, -- لتخزين ملفات الـ Base64 أو الروابط
    file_name TEXT,
    assigned_students JSONB DEFAULT '[]'::jsonb, -- قائمة معرفات الطلاب المخصص لهم الملف
    questions JSONB DEFAULT '[]'::jsonb, -- مصفوفة الأسئلة للاختبارات
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. إنشاء جدول التسليمات (مشاريع الطلاب وحلول الاختبارات)
CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT REFERENCES content(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    student_name TEXT NOT NULL,
    date TEXT DEFAULT (CURRENT_DATE)::TEXT,
    link TEXT, -- رابط Github أو Drive
    file_data TEXT, -- ملف الحل
    file_name TEXT,
    status TEXT DEFAULT 'submitted',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. إضافة حساب المدير الافتراضي
-- ملاحظة: كلمة المرور هي '123'
INSERT INTO users (username, password, role, name, active)
VALUES ('admin', '123', 'admin', 'مدير النظام', true);

-- 6. تفعيل الصلاحيات (Disable RLS)
-- يتم تعطيل الـ RLS حالياً لضمان عمل التطبيق مباشرة بدون تعقيدات السياسات
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE content DISABLE ROW LEVEL SECURITY;
ALTER TABLE submissions DISABLE ROW LEVEL SECURITY;

-- 7. منح الصلاحيات للمستخدم المجهول (Anon Key)
-- لضمان أن مفتاح الـ Anon Key الخاص بك يستطيع القراءة والكتابة
GRANT ALL ON TABLE users TO anon;
GRANT ALL ON TABLE content TO anon;
GRANT ALL ON TABLE submissions TO anon;
GRANT ALL ON SEQUENCE users_id_seq TO anon;
GRANT ALL ON SEQUENCE content_id_seq TO anon;
GRANT ALL ON SEQUENCE submissions_id_seq TO anon;
